-- Run this script while connected as the target tenant schema user.

CREATE TABLE USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    -- Stored for audit/cross-schema traceability even in schema-per-tenant deployments.
    TENANT_ID VARCHAR2(64) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(256) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    IS_ACTIVE NUMBER(1, 0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UX_USERS_USERNAME UNIQUE (USERNAME)
);
/
CREATE INDEX IX_USERS_EMAIL ON USERS (EMAIL);
/
CREATE TABLE CONTACTS (
    ID VARCHAR2(36) PRIMARY KEY,
    TENANT_ID VARCHAR2(64) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(256),
    PHONE VARCHAR2(32),
    ADDRESS VARCHAR2(500),
    METADATA_JSON CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_CONTACTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_CONTACTS_METADATA_JSON CHECK (METADATA_JSON IS JSON)
);
/
CREATE TABLE SESSIONS (
    SESSION_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    TENANT_ID VARCHAR2(64) NOT NULL,
    REFRESH_TOKEN_HASH VARCHAR2(64) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SESSIONS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
/
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATED_AT
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONTACTS_UPDATED_AT
BEFORE UPDATE ON CONTACTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE INDEX IX_CONTACTS_USER_UPDATED ON CONTACTS (USER_ID, UPDATED_AT DESC);
/
CREATE INDEX IX_CONTACTS_USER_EMAIL ON CONTACTS (USER_ID, EMAIL);
/
CREATE INDEX IX_SESSIONS_USER_EXPIRES ON SESSIONS (USER_ID, EXPIRES_AT);
/
CREATE INDEX IX_SESSIONS_EXPIRES ON SESSIONS (EXPIRES_AT);
/
