-- Run this script once per tenant schema by replacing <TENANT_SCHEMA>.

CREATE TABLE <TENANT_SCHEMA>.USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    TENANT_ID VARCHAR2(64) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(256) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    IS_ACTIVE NUMBER(1, 0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UX_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE <TENANT_SCHEMA>.CONTACTS (
    ID VARCHAR2(36) PRIMARY KEY,
    TENANT_ID VARCHAR2(64) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(256),
    PHONE VARCHAR2(32),
    ADDRESS VARCHAR2(500),
    METADATA_JSON CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_CONTACTS_USERS FOREIGN KEY (USER_ID) REFERENCES <TENANT_SCHEMA>.USERS(ID) ON DELETE CASCADE
);

CREATE TABLE <TENANT_SCHEMA>.SESSIONS (
    SESSION_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    TENANT_ID VARCHAR2(64) NOT NULL,
    REFRESH_TOKEN VARCHAR2(4000) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SESSIONS_USERS FOREIGN KEY (USER_ID) REFERENCES <TENANT_SCHEMA>.USERS(ID) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER <TENANT_SCHEMA>.TRG_USERS_UPDATED_AT
BEFORE UPDATE ON <TENANT_SCHEMA>.USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER <TENANT_SCHEMA>.TRG_CONTACTS_UPDATED_AT
BEFORE UPDATE ON <TENANT_SCHEMA>.CONTACTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE INDEX IX_CONTACTS_USER_UPDATED ON <TENANT_SCHEMA>.CONTACTS (USER_ID, UPDATED_AT DESC);
CREATE INDEX IX_CONTACTS_USER_EMAIL ON <TENANT_SCHEMA>.CONTACTS (USER_ID, EMAIL);
CREATE INDEX IX_SESSIONS_USER_EXPIRES ON <TENANT_SCHEMA>.SESSIONS (USER_ID, EXPIRES_AT);
