apiVersion: v1
kind: Secret
metadata:
  name: oracle-wallet
  namespace: effinsty
type: Opaque
data:
  cwallet.sso: BASE64_WALLET_FILE
  ewallet.p12: BASE64_WALLET_FILE
  tnsnames.ora: BASE64_TNSNAMES
  sqlnet.ora: BASE64_SQLNET
